#Create a 2D Numpy Array

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [5]:
# To Create a list
a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [6]:
# To Convert list to Numpy Array
A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [7]:
# We can use the attribute to obtain the number of axes or dimensions, referred to as the rank.
# To Show the numpy array dimensions
A.ndim

2

In [9]:
# Attribute shape returns a tuple corresponding to the size or number of each dimension.
# To Show the numpy array shape
A.shape

(3, 3)

In [10]:
#The total number of elements in the array is given by the attribute size.
#To Show the numpy array size
A.size

9

#Accessing different elements of a Numpy Array

In [11]:
# To Access the element on the second row and third column
A[1, 2]

23

In [12]:
# To Access the element on the first row and first column
A[0][0]

11

In [15]:
# To Access the element on the first and second rows and third column
A[0:2, 2]

array([13, 23])

#Basic Operations

In [16]:
# To Create a numpy array X
X = np.array([[1, 0], [0, 1]])
X

array([[1, 0],
       [0, 1]])

In [17]:
# To Create a numpy array Y
Y = np.array([[2, 1], [1, 2]])
Y

array([[2, 1],
       [1, 2]])

In [18]:
#To Add X and Y
Z = X + Y
Z

array([[3, 1],
       [1, 3]])

In [19]:
#To Create a numpy array Y
Y = np.array([[2, 1], [1, 2]])
Y

array([[2, 1],
       [1, 2]])

In [20]:
#To Multiply Y with 2
Z = 2 * Y
Z

array([[4, 2],
       [2, 4]])

In [22]:
#To Multiply X with Y
X = np.array([[1, 0], [0, 1]])
Y = np.array([[2, 1], [1, 2]])
Z = X * Y
Z

array([[2, 0],
       [0, 2]])

# To perform matrix multiplication with the numpy arrays A and B as follows:


In [30]:
# Create a matrix A and B
A = np.array([[0, 1, 1], [1, 0, 1]])
B = np.array([[1, 1], [1, 1], [-1, 1]])

# To Calculate the dot product
Z = np.dot(A,B)
Z

array([[0, 2],
       [0, 2]])

In [24]:
#To Calculate the sine of Z
np.sin(Z)

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

In [28]:
# Transposed Matrix
C = np.array([[1,1],[2,2],[3,3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [29]:
# Transposed of C
C.T

array([[1, 2, 3],
       [1, 2, 3]])